### ISSUE TITLE
Subordinate units are not shown in the unit list

### ISSUE THREAD

**Issue by hatched** [canonical/jaas-dashboard#1004]
To reproduce:
```
juju deploy cs:nagios
juju deploy cs:nrpe
juju deploy cs:ubuntu
juju relate nagios nrpe
juju relate ubuntu nrpe
```

Once everything finishes deploying when running `juju status` you'll see that we have an `nrpe` unit:

```
Unit       Workload  Agent  Machine  Public address  Ports          Message
nagios/0*  active    idle   0        18.232.96.79    80/tcp         ready
ubuntu/0*  active    idle   1        3.91.19.92
  nrpe/0*  active    idle            3.91.19.92      icmp,5666/tcp  Ready (source version/commit 75b97f3-...)
```

But in the UI we don't list one. It's important to list them here as without it we cannot run actions on subordinate charms.

![Screen Shot 2021-05-20 at 3 26 11 PM](https://user-images.githubusercontent.com/532033/119053010-af211500-b982-11eb-844e-512040ecdcd1.png)

**Comment by huwshimi** [comment]
It appears this has been resolved:

<img width="1433" alt="Screen Shot 2022-09-20 at 11 32 43 am" src="https://user-images.githubusercontent.com/361637/191147760-07c0facf-13cb-49ac-809b-0600cda52f8e.png">
<img width="1433" alt="Screen Shot 2022-09-20 at 11 32 56 am" src="https://user-images.githubusercontent.com/361637/191147770-ca6c3c30-b0a9-441b-b372-b6945555160a.png">
