### ISSUE TITLE
Machines tab incorrect for subordinates

### ISSUE THREAD

**Issue by hatched** [canonical/jaas-dashboard#1005]
To reproduce:
```
juju deploy cs:nagios
juju deploy cs:nrpe
juju deploy cs:ubuntu
juju relate nagios nrpe
juju relate ubuntu nrpe
```

The messaging says "There are no machines in this model". This isn't correct as it's just the subordinate that doesn't have a machine. However with #1004 resolved we should probably list the machines that those units are living on to provide an easy navigation point.

It also says 2 started machines but there is only a single machine that's related to this subordinate.

- [ ] Incorrect messaging
- [ ] Machine count is wrong

![Screen Shot 2021-05-20 at 3 49 11 PM](https://user-images.githubusercontent.com/532033/119053231-032bf980-b983-11eb-89aa-d9378712e23b.png)

```
➜  ~ juju status --relations
App     Version  Status  Scale  Charm   Store       Channel  Rev  OS      Message
nagios           active      1  nagios  charmstore            44  ubuntu  ready
nrpe             active      1  nrpe    charmstore            73  ubuntu  Ready (source version/commit 75b97f3-...)
ubuntu  18.04    active      1  ubuntu  charmstore            18  ubuntu

Unit       Workload  Agent  Machine  Public address  Ports          Message
nagios/0*  active    idle   0        18.232.96.79    80/tcp         ready
ubuntu/0*  active    idle   1        3.91.19.92
  nrpe/0*  active    idle            3.91.19.92      icmp,5666/tcp  Ready (source version/commit 75b97f3-...)

Machine  State    DNS           Inst id              Series  AZ          Message
0        started  18.232.96.79  i-0400d2a53d4d5af6e  bionic  us-east-1a  running
1        started  3.91.19.92    i-045dac001b384e31d  bionic  us-east-1b  running

Relation provider  Requirer           Interface  Type         Message
nrpe:monitors      nagios:monitors    monitors   regular
ubuntu:juju-info   nrpe:general-info  juju-info  subordinate
```

**Comment by huwshimi** [comment]
This has been resolved:

<img width="1433" alt="Screen Shot 2022-09-20 at 11 34 53 am" src="https://user-images.githubusercontent.com/361637/191147988-304e4864-5c96-4baa-b110-bbd0d54b04c1.png">
