### ISSUE TITLE
Unable to navigate to a subordinate in the parents unit list

### ISSUE THREAD

**Issue by hatched** [canonical/jaas-dashboard#1006]
To reproduce:
```
juju deploy cs:nagios
juju deploy cs:nrpe
juju deploy cs:ubuntu
juju relate nagios nrpe
juju relate ubuntu nrpe
```

Clicking on the `nrpe` row here does nothing. It should take you to the `nrpe` application details page.

![Screen Shot 2021-05-20 at 3 53 18 PM](https://user-images.githubusercontent.com/532033/119053630-91a07b00-b983-11eb-8750-010668f8062b.png)

**Comment by huwshimi** [comment]
Click this row now takes you to the unit page.
