### ISSUE TITLE
Incorrect machine count on application details page

### ISSUE THREAD

**Issue by hatched** [canonical/jaas-dashboard#1007]
To reproduce:
```
juju deploy cs:nagios
juju deploy cs:nrpe
juju deploy cs:ubuntu
juju relate nagios nrpe
juju relate ubuntu nrpe
```

This should only show the count for the application, not for the whole model.

![Screen Shot 2021-05-20 at 3 55 04 PM](https://user-images.githubusercontent.com/532033/119053799-ce6c7200-b983-11eb-938a-ab371b9effbb.png)

**Comment by huwshimi** [comment]
This appears to have been resolved:

<img width="1433" alt="Screen Shot 2022-09-20 at 11 37 30 am" src="https://user-images.githubusercontent.com/361637/191148258-f6bc637a-5926-4c83-9cfa-06180d83b903.png">
