### ISSUE TITLE
When a user does not have access to any models, they see a forever spinner

### ISSUE THREAD

**Issue by barrymcgee** [canonical/jaas-dashboard#1012]
**Describe the bug**

When a user does not have access to any models, they see a forever spinner

**To Reproduce**
Spin up the dashboard while logged in as a user without access to any models.

**Expected behaviour**
You should see a short spinner followed by a message informing you that you don't currently have access to any models but here is a link to the documentation to add a model.

**Comment by clagom** [comment]
(pasting my message from the duplicate issue)

This is an issue when users without models log-in (first time or not) to the JAAS dashboard (on jaas.ai/models) without having deployed models.
All we display at the moment is the spinner. Users can access to controller page, but models page displays just the spinner. Initially, the username is not visible on the bottom-left, it appears when clicking on "controllers" or on "models" again.

Maybe we can take guidelines from the recent work of @amylily1011 and @wgx on empty states. Not a complete "onboarding" experience yet, but would help users without models.

**Comment by wgx** [comment]
Here's an example of an empty state for the whole dashboard:

![image](https://user-images.githubusercontent.com/930099/122520149-29d56280-d00b-11eb-888d-3d5de24c3e1d.png)

**Comment by barrymcgee** [comment]
🙌🏻

**Comment by huwshimi** [comment]
@barrymcgee thanks Barry!
