### ISSUE TITLE
Populating "Action Message" field not possible

### ISSUE THREAD

**Issue by erik78se** [canonical/jaas-dashboard#1035]
GUI 0.7.1

Can't find any information on how to populate the "Action Message" field from the actions pane.

* The operator example documentation doesn't cover this 
* The only way to get something in here is to fail the action: 

`event.fail("some message")
`
![image](https://user-images.githubusercontent.com/850603/121096697-fddc0500-c7f2-11eb-9d77-ac31a18c7fff.png)

* No info in the docs here: https://discourse.charmhub.io/t/actions-for-the-charm-author/1113
* No info in the docs here: https://juju.is/docs/sdk/actions  (The example doesn't not produce the desired outcome e.g. setting any value)
* Also, no information that event.fail("some text")  actually sets that field. It should be mentioned to allow a developer to use that information to set meaningful messages for the operator.

**Comment by hatched** [comment]
You're right the "Action Message" field is a bit confusing right now and we may rename it or remove it entirely in upcoming releases as it doesn't work as one would expect it to. This is actually just the first step towards the full implementation. You can see the end goal in the mockup below You'll note that in this we have the various output options split out in the drop down as this fits the output from the various action formats better.

![III  Action logs - Default view](https://user-images.githubusercontent.com/532033/121119328-a6c93680-c7d8-11eb-8ffd-c11db7722bb7.png)

**Comment by erik78se** [comment]
I've logged duplicates of this. There must be something I can do to get something in there?
