### ISSUE TITLE
Information about "actions" for updating model user access

### ISSUE THREAD

**Issue by erik78se** [canonical/jaas-dashboard#1037]
GUI v0.7.1

When users are added as having access to a model, with "write" access, a user can also run actions. This is very important information when users are added access to a model.

The information is missing in the GUI

![image](https://user-images.githubusercontent.com/850603/121098472-36311280-c7f6-11eb-9967-d099fbbcb48f.png)

**Comment by hatched** [comment]
Sure we can add that 👍

**Comment by erik78se** [comment]
Is actions not available also to write level access?

Den ons 8 mars 2023 23:07huwshimi ***@***.***> skrev:

**Comment by huwshimi** [comment]
> Is actions not available also to write level access?

After staring at this question for a couple of minutes I realised I added the help to the wrong radio button. Thank you!
