### ISSUE TITLE
[Sharing] Removing users intermittedly fails

### ISSUE THREAD

**Issue by barrymcgee** [canonical/jaas-dashboard#1038]
When viewing a list of users who have access to a particular model, you can them remove them and have this action intermittently fail. 

This means, the animation to fade out the card runs but the card doesn't unmount leaving a space between the cards. e.g.

<img width="687" alt="Screenshot 2021-06-08 at 16 37 26" src="https://user-images.githubusercontent.com/505570/121215359-d713e200-c877-11eb-9e42-bba4dcdfbccd.png">

Having logged the response from Juju for this `revoke` request, it would seem the response for successful and failed requests is the same:

<img width="439" alt="Screenshot 2021-06-08 at 15 01 31" src="https://user-images.githubusercontent.com/505570/121215485-f7dc3780-c877-11eb-8c0a-a1ca815c54aa.png">

Needs more investigation.

**Comment by hatched** [comment]
RPC Calls:

Failed request:
```json
{
  "type": "ModelManager",
  "request": "ModifyModelAccess",
  "version": 5,
  "params": {
    "changes": [
      {
        "access": "write",
        "action": "revoke",
        "model-tag": "model-dc4ce753-8de6-4908-885c-0f8fc001db2a",
        "user-tag": "user-huwshimi@external"
      }
    ]
  },
  "request-id": 71
}

{ "request-id": 71, "response": { "results": [{}] } }
```

Successful request:
```json
{
  "type": "ModelManager",
  "request": "ModifyModelAccess",
  "version": 5,
  "params": {
    "changes": [
      {
        "access": "read",
        "action": "revoke",
        "model-tag": "model-dc4ce753-8de6-4908-885c-0f8fc001db2a",
        "user-tag": "user-huwshimi@external"
      }
    ]
  },
  "request-id": 26
}


{ "request-id": 26, "response": { "results": [{}] } }
```

**Comment by hatched** [comment]
Juju bug: https://bugs.launchpad.net/juju/+bug/1931619

**Comment by huwshimi** [comment]
It looks like this might be to do with how we revoke permissions. It appears that if you remove a user with "admin" permissions they will reappear with "write" permissions and if you remove a user with "write" permissions they reappear with "read" permissions and if you remove a user with "read" permissions they finally get removed.
