### ISSUE TITLE
No field validation when sharing a model

### ISSUE THREAD

**Issue by clagom** [canonical/jaas-dashboard#1051]
Probably we cannot have this functionality now, but would be good for the future to have a feedback to the users when the entry is not validated. At the moment I can entry anything but there's no negative feedback, the text disappears and that's it.

![Screenshot 2021-06-15 at 15.48.06.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/f316ee2e-fe5c-4820-bdc5-a235868c9d89)

**Comment by hatched** [comment]
Thanks, yeah this isn't technically possible right now due to limitations in the identity providers but we can keep this open to track this feature for when it becomes possible.

**Comment by huwshimi** [comment]
This displays an error now:

<img width="366" alt="Screen Shot 2022-09-20 at 12 58 04 pm" src="https://user-images.githubusercontent.com/361637/191157687-bf1a7062-03d7-4ec5-9742-fe951d8e9640.png">
