### ISSUE TITLE
[share models] Indicate to the users the value they need to input

### ISSUE THREAD

**Issue by clagom** [canonical/jaas-dashboard#1052]
![Screenshot 2021-06-16 at 09.20.09.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/d8baa48e-0acd-42e7-a078-38fb28be5da4)
If you are not a juju/jaas user you may not be aware that you need to input the username together with "@external" in the field to really add a person. 
Can we indicate an example of the value, like "please add username@external" or accept also the usernames without the "@external" part?

**Comment by hatched** [comment]
- There are no data provided by any API that we have access to which can return the domains that exist on the system.
- While unlikely, a Juju environment can have multiple external identity providers and multiple possible domains.
- It's also possible that a Juju environment can have local users in addition to ones provided by an external identity provider which means that we cannot explicitly require a domain even if an external identity provider is available.

So what can we do...

We can use the existing list of users and the existing users domain to suggest that a domain may need to be provided.
- Inspect the current users identity, does it have a domain?
- Inspect the current shared users, do they have domains? 
- If domain(s) are found, indicate that a domain may be required.
- This cannot be a hard requirement on the form as there may be domains that are not represented in this sample set (if a domain is required at all).

We'll need some UX/UI work on this to make this messaging clear.

Related to #1051
