### ISSUE TITLE
Controller doesn't display cloud/region

### ISSUE THREAD

**Issue by grebennikov** [canonical/jaas-dashboard#1087]
Juju 2.9 candidate, dashboard 0.8.0

Deploying on the Equinix provider, the cli shows that the controller belongs to equinix/da while the UI shows "Unknown/unknown"

> $ juju controllers
Use --refresh option with this command to see the latest information.

Controller  Model  User   Access     Cloud/Region  Models  Nodes    HA  Version
equinix*    k8s2   admin  superuser  equinix/da         4      1  none  2.9.8
![Screenshot from 2021-07-12 17-23-00](https://user-images.githubusercontent.com/7684958/125363543-6cead300-e336-11eb-830b-c8ad4a53155a.png)

**Comment by grebennikov** [comment]
Only impacts the "controllers" tab - models view works correctly

![Uploading Screenshot from 2021-07-12 17-40-26.png…]()

**Comment by huwshimi** [comment]
Related: https://github.com/canonical/jaas-dashboard/issues/629
