### ISSUE TITLE
Search and filter stretches header

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/jaas-dashboard#1105]
![image](https://user-images.githubusercontent.com/2741678/128493536-005e6630-7586-44f0-9521-ed374e4cbe6f.png)

Expected behaviour: The search should become part of the popup and leave the header as is.

**Comment by huwshimi** [comment]
This now limits the input to one line:

<img width="906" alt="Screen Shot 2022-09-20 at 1 25 29 pm" src="https://user-images.githubusercontent.com/361637/191160734-3b5d315c-7aea-47b4-8d10-1fddf22c3923.png">
