### ISSUE TITLE
Model access is only showing the owner 

### ISSUE THREAD

**Issue by hatched** [canonical/jaas-dashboard#1195]
**Describe the bug**
When viewing the model access pane it's only showing the owner of the model and not any other users that have access.

Adding new users doesn't add those users to the user list in the UI, but they are actually added.

**To Reproduce**
View the model access pane with a model that has multiple users.
Add a new user to that model and see that the new user isn't being added to the left column.

**Screenshots**
![Screen Shot 2021-12-07 at 3 01 18 PM](https://user-images.githubusercontent.com/532033/145107725-a00dc177-84c7-483c-86f3-9d5963db6226.png)
![Screen Shot 2021-12-07 at 3 01 46 PM](https://user-images.githubusercontent.com/532033/145107727-353f7614-d80a-4f96-af0a-31ef8f7117e3.png)
<img width="413" alt="Screen Shot 2021-12-07 at 3 06 14 PM" src="https://user-images.githubusercontent.com/532033/145107729-b053e562-0c47-4d69-a4e5-c11a7b910fd9.png">

**Comment by huwshimi** [comment]
This UI appears to be behaving correctly now.
