### ISSUE TITLE
Boolean Toggle is a textbox

### ISSUE THREAD

**Issue by JamesYangLim** [canonical/jaas-dashboard#1204]
Hi, in ceph-osd zap-disk action i-really-mean-it field should be a toggle box instead of a textbox.

![image](https://user-images.githubusercontent.com/30457655/149286916-17dfc056-ebab-4843-bbee-ec66ade9bd02.png)

**Comment by huwshimi** [comment]
It looks like everything is currently being set to a text input: https://github.com/canonical/jaas-dashboard/blob/main/src/components/RadioInputBox/OptionInputs.tsx#L52.
