### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'forEach')

### ISSUE THREAD

**Issue by anthonydillon** [canonical/jaas-dashboard#1208]
This is causing issues for a demo in the field. I think the issue is coming from this line: https://github.com/canonical-web-and-design/jaas-dashboard/blob/main/src/juju/index.js#L341

Here is where the model list is loaded from the API so might be in a different shape from production: https://github.com/canonical-web-and-design/jaas-dashboard/blob/main/src/app/model-poller.js#L120

https://sentry.is.canonical.com/canonical/juju-dashboard/issues/24169/?referrer=github_plugin

```
TypeError: Cannot read properties of null (reading 'forEach')
  at None (/static/js/main.382835c6.chunk.js:1:14039)
```

**Comment by huwshimi** [comment]
@anthonydillon do you happen to remember if there were some particular steps to reproduce this?

**Comment by anthonydillon** [comment]
Thanks Huw, it was a while ago. I've assigned myself to try and find it.

**Comment by anthonydillon** [comment]
I can't replicate this anymore. So might be fixed?
