### ISSUE TITLE
Juju topology looks broken on some models

### ISSUE THREAD

**Issue by clagom** [canonical/jaas-dashboard#1209]
Some examples from the dashboard:
![Screenshot 2022-01-21 at 22.27.19.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/9c3d61c6-2387-4db1-a08d-ff6f14ecd5d0)

![Screenshot 2022-01-21 at 22.28.09.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/f91ac613-87d1-4db4-953a-08840377652b)

**Comment by huwshimi** [comment]
I haven't managed to reproduce this. We can reopen if we find it happening again.
