### ISSUE TITLE
Controllers count shows 1 when there are 2

### ISSUE THREAD

**Issue by anthonydillon** [canonical/jaas-dashboard#1216]
On the controllers view the count in the header only shows 1 when there are more controllers in the list.

**Comment by huwshimi** [comment]
This appears to be displaying the correct count now:

<img width="951" alt="Screen Shot 2022-09-20 at 2 36 53 pm" src="https://user-images.githubusercontent.com/361637/191168632-57db20fc-2385-4d52-9004-eed237a39bc7.png">
