### ISSUE TITLE
charm icon not showing on juju dashboard

### ISSUE THREAD

**Issue by herdiansah571** [canonical/jaas-dashboard#1230]
Hello,

currently I succesfully installed openstack use openstack-bundle, but if I log in into juju dashboard gui the charm icon not showing on juju dashboard like picture bellow :
![juju-dashboard](https://user-images.githubusercontent.com/66156422/169940455-80d3cf03-6914-4465-91ce-89a12a294682.png)

anyone help me to fix this issue ?

**Comment by aym-frikha** [comment]
Hello,

This issue is affecting me as well even with version 0.9.3.

Thanks

**Comment by anthonydillon** [comment]
After investigation, this is likely due to bundles or deploys using the old `cs:` store which does not provide logos anymore. Please use charmhub.io charm commands without the prefix, to see logos.

I will leave this issue open to work on a UI so that it detects this and shows a default icon.
