### ISSUE TITLE
Refreshing action log tab causes error

### ISSUE THREAD

**Issue by huwshimi** [canonical/jaas-dashboard#1242]
**Describe the bug**
When you refresh the page when view the action logs tab it has an error `TypeError: reject is not a function`

**To Reproduce**
1. Click on a model.
2. Click on the 'Action Logs' tab.
3. Refresh the page.
4. See that you get an error.

**Expected behavior**
The action logs tab should load.

**Comment by goulinkh** [comment]
Fixed in https://github.com/canonical/jaas-dashboard/pull/1236
