### ISSUE TITLE
Action logs missing result payload

### ISSUE THREAD

**Issue by erik78se** [canonical/jaas-dashboard#1277]
@goulinkh 

        > However if would like to try it, here is the [latest version](https://drive.google.com/file/d/1bbyvE-k2oYYLbGOi_ROMneJz7NZEZO7J/view?usp=sharing) of the dashboard that works with Juju version 2.9 and 3.0 beta4.

I tried it, but it doesn't seem to work.

I ran the action from the GUI which gave the action id = 25. But nothing of the output shows in the GUI.

![image](https://user-images.githubusercontent.com/850603/195145407-93a2d71a-1ba3-43e8-8b05-ace41d4d576e.png)

I can get the output from the terminal as expected.

![image](https://user-images.githubusercontent.com/850603/195145281-0d670d5b-2447-46a3-9540-7e9ab62cd10d.png)

Another observation is that the "Output" "STDOUT/STDERR" dropdown, doesn't work either.

![image](https://user-images.githubusercontent.com/850603/195146064-571177f6-3bb1-440e-b9e2-82dc051f35ec.png)

_Originally posted by @erik78se in https://github.com/canonical/jaas-dashboard/issues/1199#issuecomment-1274953806_

**Comment by goulinkh** [comment]
Hey Erik, The dropdown values are disabled if their content is empty, in your case there is no std and error output of the action.
I assume that the output of the action that is shown in the terminal is the value of `set_results` which is different from `event.log` (stdout) and `event.fail` (stderr).

We are planning to add another button that shows something like a popup with the full output of `set_results`, which I believe is important to have in the dashboard but difficult to fit in the actions logs table, let's leave this issue open to track the state of this.

**Comment by erik78se** [comment]
Right, so I would have to only use the event.log and event.fail as output
for the actions at this point?

**Comment by goulinkh** [comment]
Yes if you need them to be shown in the dashboard.

**Comment by erik78se** [comment]
Also, this is a matter of also documenting how actions work and needs to be
implemented in a charm. What information will and won't be displayed in the
interface(s) is helpful to charmers that otherwise would be left to
guesswork and trial and error.

Knowing what should be done to get output properly displayed in the various
interfaces is a must imo.

**Comment by erik78se** [comment]
I tested it with this example charm and it kind of works to a rudimentary level, also in the GUI. As you mentioned, its only displaying the event.log("Message") yet in the interface and the STDOUT and STDERR is still not working at all.

https://github.com/erik78se/juju-operators-examples/tree/main/action-charm

Its getting there though and we can start using this for sure now.

![image](https://user-images.githubusercontent.com/850603/196039624-67f49e52-d1e8-4bfc-8e79-84ba226a0407.png)
![image](https://user-images.githubusercontent.com/850603/196039644-d21b129d-5e04-4f2a-8d67-50cfb5426f1d.png)
