### ISSUE TITLE
Question version for juju 2.9

### ISSUE THREAD

**Issue by moula** [canonical/jaas-dashboard#1431]
Hi, 
Just a question for juju 2.9 and juju-dashboard 0.10 Now you have released version 0.10 for juju 3.0, will it be apply to juju 2.9 version or not? There are plenty of charms and bundles that still only work with a 2.9 controller. We're not all going to migrate to juju 3.0. 
Thank you so much.

**Comment by huwshimi** [comment]
Hi @moula there is currently an issue affecting all versions with 0.10.0, but once that is fixed it should continue to work with 2.9. If you come across any issues, please let us know!
