### ISSUE TITLE
Juju-dashboard on juju 3.1 

### ISSUE THREAD

**Issue by moula** [canonical/jaas-dashboard#1459]
Hi, I am trying to install juju-dashboard on juju version 3.1. it doesn't work completely!!! Nginx is still blocked!!!
Even the juju-dashboard command gives wrong information:
http://localhost:31666
While I connect with the ip address on port 8080.
Thank's.
![Capture d’écran du 2023-04-14 09-22-29](https://user-images.githubusercontent.com/1804815/231974407-462b18e4-9984-438e-95d7-39c819068a1e.png)
![Capture d’écran du 2023-04-14 09-21-12](https://user-images.githubusercontent.com/1804815/231974410-70acde8c-c911-4352-baec-82921b863a71.png)
![Capture d’écran du 2023-04-14 09-31-51](https://user-images.githubusercontent.com/1804815/231975118-fdeb9689-381c-4584-a384-9dcce40b4765.png)

**Comment by huwshimi** [comment]
Hi @moula if the dashboard is running correctly it may be safe to use `juju resolved ...` to mark that error as fixed.

You could also try redeploying the dashboard to see if it completes (I just tested deploying the dashboard charm on 3.1 and it finished without that error).

As for the port, when running `juju dashboard` it forwards `31666` to the dashboard but there are a couple of open bugs about the port forwarding, so rebooting your controller might resolve these:
- https://bugs.launchpad.net/juju/+bug/1995958
- https://bugs.launchpad.net/juju/+bug/1996052

**Comment by moula** [comment]
@huwshimi The problem is still there.
I just tried again with juju-dashboard and dashboard, it still doesn't work. I point out that I do it with MAAS so the juju instance is created by maas on ubuntu-22.04. The problem comes from nginx which does not select the ip of the instance as with juju.2.9 but localhost:31666. With juju 2.9 the juju dashboard command gives: http://ip:17070/dashboard.
Whereas with 3.1 gives: http://localhost:31666 
While MAAS gives the ip 127.0.0.1 when creating the instance while the ip 172.167.70.106.
Even we change the ip manually, since it is MAAS that manages the IP, it always comes back to 127.0.0.1.
![Capture d’écran du 2023-04-17 09-12-58](https://user-images.githubusercontent.com/1804815/232411334-9696581f-967f-48c6-8c2f-a028aa7f5d78.png)
Nginx does not work correctly with localhost when running :  juju deploy juju-dashboard.
Command "juju resolved dashboard/0"  does not solve the deadlock.
I hope I managed to explain the problem to you. 
I can give you remote access to my platform. The bug is still there. (Maas+juju+juju-dashboard). 
Thank's. 
![Capture d’écran du 2023-04-17 09-04-20](https://user-images.githubusercontent.com/1804815/232411946-8224012d-f266-4570-9677-57bfc30880ea.png)
![Capture d’écran du 2023-04-17 08-59-07](https://user-images.githubusercontent.com/1804815/232411955-5b3fb276-1302-434d-a732-f794747bc685.png)
![Capture d’écran du 2023-04-17 08-57-27](https://user-images.githubusercontent.com/1804815/232411959-e6e6f5a4-6830-42f1-982c-2d917af4ad56.png)

**Comment by huwshimi** [comment]
Hi @moula does this thread help answer your questions at all? https://discourse.charmhub.io/t/juju-deploy-juju-dashboard-using-juju-3-0-only-attaches-to-localhost/7338

**Comment by moula** [comment]
@huwshimi I'll look at that later. For now I'm back to version 2.9. Because most bundles and charms work on it. 
Thank you so much.
