### ISSUE TITLE
JUJU-DASHBOARD DOES NOT OPEN APPLICATIONS AND MACHINES

### ISSUE THREAD

**Issue by cleitonpena** [canonical/jaas-dashboard#1465]
When entering Juju-Dashabord in MAAS Cloud Controller the main screens Controllers and Models appear normally, but when you click on any of the options to see the applications or machines, the screen turns clear and the icon-sppiner runs infinitely. In the Web Inspector Console, the error messages:

> [Error] Failed to load resource: Origin http://localhost:31666 is not allowed by Access-Control-Allow-Origin. Status code: 403 (envelope, line 0)
> [Error] WebSocket connection to 'ws://localhost:31666/model/d1df8714-660e-4a0f-8ff6-74b4534ad877/api' failed: The operation couldn’t be completed. Socket is not connected
> [Log] -- (main.95c5cd51.js, line 2)
> Event
> bubbles: false
> cancelBubble: false
> cancelable: false
> composed: false
> currentTarget: null
> defaultPrevented: false
> eventPhase: 0
> isTrusted: true
> returnValue: true
> srcElement: WebSocket {listeners: Object, url: "ws://localhost:31666/model/d1df8714-660e-4a0f-8ff6-74b4534ad877/api", readyState: 3, bufferedAmount: 0, onopen: function, …}
> target: WebSocket {listeners: Object, url: "ws://localhost:31666/model/d1df8714-660e-4a0f-8ff6-74b4534ad877/api", readyState: 3, bufferedAmount: 0, onopen: function, …}
> timeStamp: 98687
> type: "error"
> Event Prototype

**Comment by huwshimi** [comment]
Hi @cleitonpena which versions of the dashboard and Juju are you running? Also, how did you deploy the dashboard, was it via the charm or via the controller?
