### ISSUE TITLE
Topology re-renders periodically

### ISSUE THREAD

**Issue by hatched** [canonical/jaas-dashboard#430]
If you sit on a model details page and watch the topology, expanded or not, it will re-render itself periodically. I feel like it's happening whenever the status update returns but I haven't investigated to confirm that. 

This only appears to happen in Chrome however that might be a red herring...

**Comment by barrymcgee** [comment]
@hatched I've dug into this a bit more and think I'm pretty sure it's due to `ModelsDetails` re-rendering periodically and thus all of its children following suit. Are we memoising the data coming into ModelDetails correctly so it's checking if that data has actually changed before rerendering?

**Comment by anthonydillon** [comment]
While working on the model details page today I have noticed the relations table is rerendered in a different order often. If the polling is returning the relations data in a different order then React will assume its new data. You could try sorting the relations before storing it so the list in the store so the diff in the store is empty.

**Comment by hatched** [comment]
To help unblock @barrymcgee on #244 I'll hop onto this now.

**Comment by hatched** [comment]
As I'm working on this, @barrymcgee if this is causing issues for you, you can remove `applications` and `relations` from [this line](https://github.com/canonical-web-and-design/jaas-dashboard/blob/master/src/components/Topology/Topology.js#L262). There don't appear to be many negative side effects because the topology isn't being updated out of band too often.

**Comment by hatched** [comment]
After some investigation this is happening because the applications and relations arrays are re-generated on every render causing them to be 'different' arrays, even though their values are the same. We will have to implement/use a new `useEffect` that supports deep comparisons. I originally thought we could implement a simpler data structure generated by a memoized function. However the objects that would be passed to the `useMemo` change often so it would re-generate the memoized value which would still trigger the `useEffect` to rerun.

While there is certainly performance implications to resolving the multiple re-renders I'm not sure that the above re-rendering is as big of an issue... 

If applications or relations are added or removed in the model we need the Topology to re-render to update with the new data, regardless if you're interacting with it or not. The root issue here is that the parent <svg> should never be re-rendered and `d3` should only be updating the content that's changed, not the whole svg when it receives new data. 

I'm going to park this issue as work to resolve that issue is in the same area that @barrymcgee is working to implement the topology re-positioning and it can be revisited after that's landed.

**Comment by huwshimi** [comment]
This is still an issue:

![Screen Recording 2022-09-19 at 1 45 38 pm](https://user-images.githubusercontent.com/361637/190946632-b06102c4-e7e1-42a8-b67b-065e62dcaf1c.gif)
