### ISSUE TITLE
Vis does not render correctly on small screens

### ISSUE THREAD

**Issue by anthonydillon** [canonical/jaas-dashboard#434]
It looks like the mask that is making the icons round are not resizing. Also the main width and height seem wrong.

**Expected behavior**
The model vis should always look 👌

**Screenshots**
![Screenshot_20200417-201353](https://user-images.githubusercontent.com/1413534/79606076-f0445700-80e8-11ea-8022-01673fad466a.jpg)

**Smartphone (please complete the following information):**
 - Device: oneplus
 - OS: android 10
 - Browser chrome
 - Version latest

**Comment by hatched** [comment]
After doing some testing, this issue is only present on the aforementioned browser/OS combo. It works as expected on desktop browsers and Android 10 w/Firefox.

**Comment by huwshimi** [comment]
I have seen this in the past, but it no longer seems to be an issue.
