### ISSUE TITLE
Fix the position of the Topology column when scrolling

### ISSUE THREAD

**Issue by clagom** [canonical/jaas-dashboard#517]
For long models, would be useful to have the topology view/column sticky when scrolling.
Mockup
![Screenshot 2020-05-27 at 11.25.43.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/41cd0bb1-8abd-4ea3-8313-1f55bfa7d3e9)

![Screenshot 2020-05-27 at 11.25.15.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/91cf70b9-5846-45dd-b25e-cc9f4e002158)

**Comment by hatched** [comment]
Your drawings are on point! :)

**Comment by clagom** [comment]
I forgot to use pink for the colour of the annotations 😅
