### ISSUE TITLE
Status column does not truncate

### ISSUE THREAD

**Issue by anthonydillon** [canonical/jaas-dashboard#530]
The status column has the value "Unknown" truncated at 1679px.
<img width="458" alt="Screen Shot 2020-05-28 at 9 17 25 PM" src="https://user-images.githubusercontent.com/532033/83217327-b70bf780-a128-11ea-8fdd-5e1fce5b55fc.png">

**Comment by hatched** [comment]
The same column on the Unit side...

![Screen Shot 2020-06-01 at 1 30 49 PM](https://user-images.githubusercontent.com/532033/83446627-3725ac00-a40c-11ea-8f83-a241f9b3d41d.png)

**Comment by huwshimi** [comment]
This still appears to be an issue on the Machines tab:

<img width="1041" alt="Screen Shot 2022-09-19 at 3 44 06 pm" src="https://user-images.githubusercontent.com/361637/190956111-bc670813-8caa-44f2-be4f-41e6e0b2f7e2.png">
