### ISSUE TITLE
Some truncated columns do not provide tooltips

### ISSUE THREAD

**Issue by anthonydillon** [canonical/jaas-dashboard#531]
IP addresses are truncated at the minimum width but there isn't a title to get the actual value.
Statuses are truncated without an ellipsis and are also no tooltip.
<img width="686" alt="Screen Shot 2020-05-28 at 9 22 23 PM" src="https://user-images.githubusercontent.com/532033/83217637-72cd2700-a129-11ea-8cf6-dd1a1056ea2a.png">

**Comment by huwshimi** [comment]
Related: https://github.com/canonical/jaas-dashboard/issues/973

**Comment by huwshimi** [comment]
Related: https://github.com/canonical/jaas-dashboard/issues/508
