### ISSUE TITLE
SVG scale level resets to 1 when initiating zoom

### ISSUE THREAD

**Issue by barrymcgee** [canonical/jaas-dashboard#556]
- Open model details page
- Expand topology
- Move mouse wheel
- See svg reset to scale level reset to 1

<img width="1440" alt="Screenshot 2020-06-16 at 14 18 35" src="https://user-images.githubusercontent.com/505570/84779522-6c212980-afdc-11ea-8600-22c5afe11a45.png">

**Comment by huwshimi** [comment]
I can't reproduce this in Chrome or Firefox.
