### ISSUE TITLE
Negative values app co-ordinate bug

### ISSUE THREAD

**Issue by barrymcgee** [canonical/jaas-dashboard#559]
When expanding the svg, the apps on the lower right move further away each time

<img width="905" alt="Screenshot 2020-06-16 at 14 42 03" src="https://user-images.githubusercontent.com/505570/84782125-91fbfd80-afdf-11ea-9c38-b95782591d99.png">

**Comment by huwshimi** [comment]
It looks like this was related to some work that was dropped.
