### ISSUE TITLE
Make 'configuration' icons link to model details section

### ISSUE THREAD

**Issue by hatched** [canonical/jaas-dashboard#596]
<img width="196" alt="Screen Shot 2020-07-16 at 11 58 14 AM" src="https://user-images.githubusercontent.com/532033/87705781-a60c5980-c75b-11ea-8ca6-25be780b2396.png">

For now these can go to the model details page but in the future we will want them to go to the specific subsection for `units`, `machines`, etc

**Comment by spencerbygraves** [comment]
@hatched design for reference - https://zpl.io/a7AZxxR
