### ISSUE TITLE
Error when logging in looks ugly

### ISSUE THREAD

**Issue by anthonydillon** [canonical/jaas-dashboard#646]
The model when login fails is ugly:
![image](https://user-images.githubusercontent.com/1413534/89796076-17ec7e80-db21-11ea-800a-52b7711c0c06.png)

## Replicate
- Log into https://staging.login.ubuntu.com
- When go to the dashboard and login

**Comment by hatched** [comment]
I think your steps are a red herring. It looks like you have a bad macaroon.

So the remedy is twofold...
- [ ] The error is ugly and unhelpful. We should be able to inspect this type of response and provide a more helpful error message.
- [ ] We should be able to see the type of error on login and if the macaroon is invalid, clear it, and request a new one. This may require that we present an error that the user must click to visit the third party identity service.

**Comment by huwshimi** [comment]
I can't reproduce this at the moment, but I think that's because the errors aren't being displayed: https://github.com/canonical/jaas-dashboard/issues/867.

**Comment by huwshimi** [comment]
I think these are all resolved, but we might need to reopen if we discover a case we haven't handled.

<img width="364" alt="Screenshot 2023-04-05 at 1 30 45 pm" src="https://user-images.githubusercontent.com/361637/229974332-49dc2939-ce61-4fbf-98ac-f41f5f44fd07.png">
