### ISSUE TITLE
Public data is undefined in additional controllers

### ISSUE THREAD

**Issue by anthonydillon** [canonical/jaas-dashboard#647]
![image](https://user-images.githubusercontent.com/1413534/89796999-428b0700-db22-11ea-9d67-f6860ae02d44.png)

**Comment by hatched** [comment]
Looks like this is a bug here: https://github.com/canonical-web-and-design/jaas-dashboard/blob/master/src/pages/Controllers/Controllers.js#L96

**Comment by huwshimi** [comment]
I think this is the line linked to above (the first case is always truthy so `False` is never displayed: https://github.com/canonical/jaas-dashboard/blob/1844536645736e0eec057c453c09213936cc66a7/src/pages/ControllersIndex/ControllersIndex.js#L112.

**Comment by huwshimi** [comment]
This was fixed in #1366.
