### ISSUE TITLE
Align columns on the details page

### ISSUE THREAD

**Issue by hatched** [canonical/jaas-dashboard#700]
The columns on the details page have gotten pushed around and need to be re-aligned.

![image](https://user-images.githubusercontent.com/9105999/94279603-3fb66b00-ff44-11ea-9169-643583c26e86.png)

re: https://github.com/canonical-web-and-design/jaas-dashboard/pull/693#issuecomment-698963973

**Comment by ziheliu214** [comment]
@ziheliu214 @long-chung to update the latest design here and check if we need to align

**Comment by huwshimi** [comment]
This UI has changed quite a bit, but it looks like you can still have three tables.

<img width="1437" alt="Screen Shot 2022-09-20 at 10 24 41 am" src="https://user-images.githubusercontent.com/361637/191141514-aa81bbc3-08a8-49a0-bd25-9030127012b6.png">

**Comment by huwshimi** [comment]
I'm going to close this for now as the way it is designed is that each table can have independent horizontal scrolling so there's no sensible way to have same size columns.
