### ISSUE TITLE
When zooming out topology, the icons of the charms are getting small and not aligned with the container-circle

### ISSUE THREAD

**Issue by ziheliu214** [canonical/jaas-dashboard#813]
![image](https://user-images.githubusercontent.com/61144986/103886140-f7791e00-50d8-11eb-994c-b0d6862d4d79.png)

**Comment by hatched** [comment]
Thanks for the bug report @ziheliu214, how do you reproduce this?

**Comment by ziheliu214** [comment]
> Thanks for the bug report @ziheliu214, how do you reproduce this?

Hey just zoom out from your browser `CMD`+ `-`

**Comment by hatched** [comment]
Ahh great thanks

**Comment by huwshimi** [comment]
This appears to have been resolved.
