### ISSUE TITLE
Config inputs do not validate and fail silently

### ISSUE THREAD

**Issue by barrymcgee** [canonical/jaas-dashboard#849]
- Go to CMR model and click Logstash app
- Click Configure
- Enter a letter in 'beats_port' field
- Click Save
- Saving fails silently

<img width="1280" alt="Screenshot 2021-01-29 at 10 15 27" src="https://user-images.githubusercontent.com/505570/106267355-6a317100-6221-11eb-91cd-46ab1f3872ee.png">

**Comment by hatched** [comment]
Yep this is known, validation and error reporting haven't yet been implemented. I'll leave this open until that has happened.
