### ISSUE TITLE
Disable topology zoom on mobile view

### ISSUE THREAD

**Issue by clagom** [canonical/jaas-dashboard#859]
Topology looks small in the modal zoomed-in window, it's at the bottom

![image](https://user-images.githubusercontent.com/1953388/106819230-65c9e580-6671-11eb-9801-913290f96a57.jpeg)

**Comment by hatched** [comment]
I think we should just remove this zoom interaction entirely on mobile as it doesn't really provide any benefit over the full width topology that's already visible.

**Comment by anthonydillon** [comment]
I think zooming is more useful on mobile as the full view it likely to small to see detail.

**Comment by clagom** [comment]
Agree with @anthonydillon

**Comment by hatched** [comment]
Sorry what I meant was the 'zoomed view' (the one that opens when you click the [ ] )should be disabled as the actual topology will gain pan and zoom.

That topology is full width on a mobile screen already (or should be).

**Comment by anthonydillon** [comment]
Can we plan zoom the canvas? I would agree if that was the case

**Comment by hatched** [comment]
technically it's disabled because it's buggy but yep it can pan/zoom so we can dedicate some time to resolving those issues.
