### ISSUE TITLE
On mobile the + is hard to tap. Use the actions expander for config view

### ISSUE THREAD

**Issue by clagom** [canonical/jaas-dashboard#860]
![image](https://user-images.githubusercontent.com/1953388/106819427-b0e3f880-6671-11eb-85a3-efcf61c2e3de.png)

**Comment by hatched** [comment]
Heh I actually had it as the whole title but it ended up causing issues with accessibility. Maybe we can instead just increase the whole clickable area to the all of the padding surrounding the +.

**Comment by barrymcgee** [comment]
It's generally recommended any tap target should be at least 44px square as per Apple's [Human Interface Guidelines](https://developer.apple.com/ios/human-interface-guidelines/visual-design/adaptivity-and-layout/).

**Comment by cristinadresch** [comment]
use the actions expander (arrow instead of +/-)
