### ISSUE TITLE
Log in error messages don't appear in the UI

### ISSUE THREAD

**Issue by hatched** [canonical/jaas-dashboard#867]
For some reason when logging in with an incorrect password it does not report the error message back to the user in the UI.

![Screen Shot 2021-02-08 at 12.13.14 PM.png](https://images.zenhubusercontent.com/5bf56fa65f3ffb2e1680062c/4d444387-cf6d-485f-8636-e841eb60e1a0)

**Comment by huwshimi** [comment]
This is also an issue if you can't connect to the controller for some reason.
