### ISSUE TITLE
If a model does not exist, we should inform the user

### ISSUE THREAD

**Issue by barrymcgee** [canonical/jaas-dashboard#906]
If a user tries to access a model that does not exist via a URL, they will crash the app. We should surface this error in a more user-friendly way.

**Comment by anthonydillon** [comment]
Can we list it with a disconnected message?

**Comment by hatched** [comment]
Basically we just need to wait until we have a response from the ModelList call and then cross reference that list with the ones they have requested. This list can be up to 30s out of date until we implement the watcher.

**Comment by anthonydillon** [comment]
I assume the way it works is you request a model list then we loop over the model list every 30s to pull the model status. If that is the case, we should render the model list immediately and as the model status data is populated the table fills up with data.

That way we can list all expected models and we can show there is an issue getting the model status.

**Comment by hatched** [comment]
Yep that's exactly what we do now. The issue is when you try and access a model directly bypassing the list screen. When that happens we still request the list but we dont reference it when trying to request the data from the model details page .
