### ISSUE TITLE
Local Apps title should be Local App

### ISSUE THREAD

**Issue by hatched** [canonical/jaas-dashboard#937]
In an applications units view there can only ever be a single app so the "Local Apps" table should not be plural. This pluralization should be based on the size of data sent to the table as the same table is used elsewhere as well.

![Screen Shot 2021-03-29 at 2 58 33 PM](https://user-images.githubusercontent.com/532033/112899503-7742d300-909f-11eb-9e05-6975b468db59.png)

**Comment by satyampgt4** [comment]
i like to work on it
