### ISSUE TITLE
Humanise date/time

### ISSUE THREAD

**Issue by anthonydillon** [canonical/jaas-dashboard#965]
**Describe the bug**
It would be nice to humanise the date/time table data and provide a label with the actual value.

**To Reproduce**
1. Go to the new actions list
2. Scroll to the  right hand column
3. See that date/time is not very useful

**Expected behavior**
I would expect something like "2 days ago" with a hover that shows the time and date.

**Screenshots**
![image](https://user-images.githubusercontent.com/1413534/115411055-0f3d6380-a1eb-11eb-9e75-2215f97f535d.png)

**Comment by hatched** [comment]
Do we have a library that we use across any other projects for this feature?

**Comment by huwshimi** [comment]
> Do we have a library that we use across any other projects for this feature?

We use https://date-fns.org/ in MAAS.
