### ISSUE TITLE
Deep linking back to jaas.ai errors

### ISSUE THREAD

**Issue by anthonydillon** [canonical/jaas-dashboard#996]
**To Reproduce**
1. Go to a model details
2. Click a logo to go to the site 
3. Then hit the back button
4. See the error

**Expected behavior**
Load the correct page

**Additional context**
Sentry issue: https://sentry.is.canonical.com/canonical/juju-dashboard/issues/17895/

**Comment by hatched** [comment]
I'm not able to reproduce, can you let me know what the path was that you were at? I don't need the specific path, just what you were viewing, unit details, controllers, etc.

**Comment by huwshimi** [comment]
It looks like this code has been updated to check for the version.
